include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - '**/*.g.dart'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    unnecessary_parenthesis: true
    avoid_init_to_null: true

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 4
    source-lines-of-code: 200
  metrics-exclude:
    - test/**
    - '**/*.g.dart'
  rules:
    - prefer-trailing-comma
    - avoid-nested-conditional-expressions
    - avoid-redundant-async
    - prefer-first
