mkdir -p .github/workflows

# write the workflow in one go (safe heredoc)
cat > .github/workflows/ci.yml <<'YAML'
name: Flutter CI

on:
  push:
    branches: [ main, "refactor/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Android builds need a modern JDK (Gradle), so set Java 17
      - name: Setup Java (for Android/Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Provision Android SDK and accept licenses
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Install Flutter and enable caching of the SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Unit & widget tests (with coverage)
        run: flutter test --coverage

      # Debug APK is enough for a “smoke compile” check on Ubuntu
      - name: Build APK (smoke compile)
        run: flutter build apk --debug

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
YAML
