mkdir -p .github/workflows

cat > .github/workflows/main.yml <<'YAML'
name: Flutter CI

on:
  push:
    branches: [ main, "refactor/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
          cache: true

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Sets ANDROID_HOME and puts sdkmanager on PATH
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Install packages explicitly (avoids the multiline parsing issue)
      - name: Install Android packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses
          sdkmanager --list | head -n 50

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Unit & widget tests (with coverage)
        run: flutter test --coverage

      - name: Build APK (smoke compile)
        run: flutter build apk --debug

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
          if-no-files-found: warn

      - name: Upload debug APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: warn
YAML
